# Generated by Django 3.2.9 on 2021-11-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('link', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms',models.DecimalField(decimal_places=1, max_digits = 3)),
                ('price', models.PositiveIntegerField()),
                ('photo',models.CharField("Photo",max_length=300)),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
