# Generated by Django 3.2.9 on 2021-11-11 23:50
import sys
from django.db import migrations
import sys
sys.path.append("../")
from craig import get_listings

def create_data(apps, schema_editor):
    Listing = apps.get_model('scrapper', 'Listing')
    listings = get_listings()
    for lst in listings:
        lst.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]