# Generated by Django 3.2.9 on 2021-11-11 23:50

from django.db import migrations

def create_data(apps, schema_editor):
    Listing = apps.get_model('scrapper', 'Listing')
    Listing(address="244 Dwight Way, Berkeley", email="JJIceSmith@gmail.com", price="2400", rooms="1",photo="https://www.propertymanagementselect.com/wp-content/uploads/2015/04/sacramento-property-management-apartments-1030x684.jpg").save()


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]