# Generated by Django 3.2.9 on 2021-11-11 23:50

from django.db import migrations
from craigslist import CraigslistHousing


def create_data(apps, schema_editor):
    Listing = apps.get_model('scrapper', 'Listing')
    data = []
    cl_h = CraigslistHousing(site='sfbay', area='eby', category='apa',
                         filters={'zip_code': "94704", 'search_distance':"1", 'max_price': 1200, 'private_room': True})
                         
    for result in cl_h.get_results(sort_by='newest', geotagged=True):
        Listing(link = result['url'], location = result['where'], description = result['name'], email = "", bedrooms = 2, bathrooms = 3, price = result['price'], photo = "", registrationDate = result['last_updated'])
        

class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]