# Generated by Django 3.2.9 on 2021-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
